###
GET http://localhost:8080/api/locations/
Accept: application/json

###
GET http://localhost:8080/api/locations/3
Accept: application/json

###
POST http://localhost:8080/api/locations
Content-Type: application/json
Accept: application/json

{
  "name": "Dunaszentpál focipálya",
  "lat": 47.78047153293665,
  "lon": 17.50511081164347
}

###
PUT http://localhost:8080/api/locations/3
Content-Type: application/json
Accept: application/json

{
  "name": null,
  "lat": 47.7802912954123,
  "lon": 17.505475592098865
}


###
DELETE http://localhost:8080/api/locations/3